# Auth_Server_start
apiVersion: v1
kind: Service
metadata:
  name: auth-server-svc
spec:
  selector:
    app: auth-server
  ports:
    - name: http
      protocol: TCP
      port: 8083
      targetPort: 8083
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
        - name: auth-server
          image: Auth_Server/auth_server:latest
