# Auth_Server_65448d46b3f896791767b6e0ed16eb0d7f76fc8f
apiVersion: v1
kind: Service
metadata:
  name: auth-server-svc
spec:
  selector:
    app: auth-server
  ports:
    - name: http
      protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 30083
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
        - name: auth-server
          image: leehb97/auth_server:latest
          ports:
            - protocol: TCP
              containerPort: 8083
