# Auth_Server_49230c0e5f924f58def1e3cc5a50088c0319c330
apiVersion: v1
kind: Service
metadata:
  name: auth-server-svc
spec:
  selector:
    app: auth-server
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
        - name: auth-server
          image: leehb97/auth_server:latest
          ports:
            - containerPort: 8083
