# Auth_Server_2c28758267ecf54c1afbf19a6a90bb90d816890d
apiVersion: v1
kind: Service
metadata:
  name: auth-server-svc
spec:
  selector:
    app: auth-server
  ports:
    - name: http
      port: 8083
      targetPort: 8083
      nodePort: 30083
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
        - name: auth-server
          image: leehb97/auth_server:latest
