# Member_Write_c46e45fc3a0b46b2dcc5eb121412c21ab4403d8b
apiVersion: v1
kind: Service
metadata:
  name: member-write-svc
spec:
  selector:
    app: member-write
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-write-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member-write
  template:
    metadata:
      labels:
        app: member-write
    spec:
      containers:
        - name: member-write
          image: leehb97/member_write:latest
          ports:
            - protocol: TCP
              containerPort: 8081
