# Member_Read_528746cd70f239abc5893726569fb3d00cc88c35
apiVersion: v1
kind: Service
metadata:
  name: member-read-svc
spec:
  selector:
    app: member-read
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-read
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member-read
  template:
    metadata:
      labels:
        app: member-read
    spec:
      containers:
        - name: member-read
          image: leehb97/member_read:latest
          ports:
            - containerPort: 8080
