# Member_Read_839a0c1c4c2bf99716715a00fc62830a78beca73
apiVersion: v1
kind: Service
metadata:
  name: member-read-svc
spec:
  selector:
    app: member-read
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30082
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-read
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member-read
  template:
    metadata:
      labels:
        app: member-read
    spec:
      containers:
        - name: member-read
          image: leehb97/member_read:latest
          ports:
            - protocol: TCP
              containerPort: 8082
