# Member_Write_f4271220dc15bc41ed554ba5465b47a64df89573
apiVersion: v1
kind: Service
metadata:
  name: member-write-svc
spec:
  selector:
    app: member-write
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30081
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-write-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member-write
  template:
    metadata:
      labels:
        app: member-write
    spec:
      containers:
        - name: member-write
          image: leehb97/member_wirte:latest
