# Member_Client_a1d1bbcbed1c01ae52810c245235b1e60f143876
apiVersion: v1
kind: Service
metadata:
  name: member-client-svc
spec:
  selector:
    app: member-client
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member-client
  template:
    metadata:
      labels:
        app: member-client
    spec:
      containers:
        - name: member-client
          image: leehb97/member_client:latest
          ports:
            - protocol: TCP
              containerPort: 80
