# Member_Write_bccb23f34631045467e114b829b93eba1ff82d7d
apiVersion: v1
kind: Service
metadata:
  name: member-write-svc
spec:
  selector:
    app: member-write
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-write-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member-write
  template:
    metadata:
      labels:
        app: member-write
    spec:
      containers:
        - name: member-write
          image: Member_Write/member_wirte:latest
